# Generated by Django 5.2.8 on 2025-11-26 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='nominee',
            options={'verbose_name': 'Номинант', 'verbose_name_plural': 'Номинанты'},
        ),
        migrations.AlterModelOptions(
            name='suggestedcategory',
            options={'verbose_name': 'Предложенная номинация', 'verbose_name_plural': 'Предложенные номинации'},
        ),
        migrations.AlterModelOptions(
            name='suggestednominee',
            options={'verbose_name': 'Предложенный номинант', 'verbose_name_plural': 'Предложенные номинанты'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'nominee')},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.category'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя номинанта'),
        ),
        migrations.AlterField(
            model_name='suggestedcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='suggestedcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название номинации'),
        ),
        migrations.AlterField(
            model_name='suggestednominee',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='suggestednominee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя номинанта'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='nominee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.nominee'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_jury', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='category',
        ),
    ]
