# Generated by Django 5.2.8 on 2025-11-26 10:24

import awards.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_category_options_alter_nominee_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardconfig',
            name='current_stage',
            field=models.CharField(choices=[('suggest_cat', 'Предложение номинаций'), ('finished', 'Этап проверки админами'), ('suggest_nominee', 'Предложение номинантов'), ('voting', 'Голосование'), ('results', 'Публикация результатов после награждения')], default='suggest_cat', max_length=30),
        ),
        migrations.CreateModel(
            name='JuryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=awards.models.default_expire)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_votes', models.PositiveIntegerField(default=0)),
                ('user_votes', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.category')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.nominee')),
            ],
            options={
                'unique_together': {('category', 'nominee')},
            },
        ),
    ]
