# Generated by Django 5.2.8 on 2025-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_awardconfig_current_stage_jurytoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardconfig',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='awardconfig',
            name='name',
            field=models.CharField(default='Онлайн-премия', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='jury',
            field=models.BooleanField(default=False),
        ),
    ]
